name: Java CI Relaese

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package -DskipTests=true

      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: scm-sync-configuration.hpi
          path: target/scm-sync-configuration.hpi

      - name: create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: target/scm-sync-configuration.hpi
